import glob
import os
from PIL import Image

def create_wavefield_gif():
    # Get the current directory
    pwd = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(pwd, "OUTPUT_FILES")
    
    # Find all forward image JPEGs generated by SPECFEM2D
    search_pattern = os.path.join(output_dir, "*image*.jpg")
    image_files = glob.glob(search_pattern)
    
    if not image_files:
        print("❌ No JPEG snapshots found in OUTPUT_FILES.")
        print("Make sure 'output_postscript_snapshot' is set to .true. in your Par_file.")
        return
        
    # Sort files numerically by their time step (so the GIF plays in forward time)
    # Extracts the numbers from 'forward_image000000500.jpg' for correct sorting
    image_files.sort(key=lambda f: int(''.join(filter(str.isdigit, os.path.basename(f)))))
    
    print(f"🎬 Found {len(image_files)} wavefield snapshots. Stitching GIF...")
    
    # Load all images into memory
    frames = [Image.open(img) for img in image_files]
    
    # Save them as a continuous looping GIF
    gif_path = os.path.join(pwd, "Wavefield_Animation.gif")
    
    # Duration is in milliseconds per frame (100ms = 10 fps)
    frames[0].save(
        gif_path,
        format='GIF',
        append_images=frames[1:],
        save_all=True,
        duration=100, 
        loop=0  # 0 means infinite loop
    )
    
    print(f"✅ GIF successfully created and saved to: {gif_path}")

if __name__ == "__main__":
    create_wavefield_gif()